# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'TruHiker' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TruHiker
  pod 'Firebase/Auth'
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'
  pod 'Crashlytics'
  pod 'Fabric'
  pod 'GoogleSignIn'

  target 'TruHikerTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
